package by.kiselevich.periodicals.command;

public enum CommandName {
    HOME,
    WRONG_REQUEST,
    SIGN_IN,
    SIGN_UP,
    SIGN_OUT,
    CHANGE_LANGUAGE,
    ADMIN_PAGE,
    SHOW_USERS,
    SHOW_EDITIONS,
    SHOW_PAYMENTS,
    SHOW_SUBSCRIPTIONS,
    BLOCK_USER,
    UNBLOCK_USER,
    ADD_EDITION,
    USER_PAGE,
    SHOW_USER_PAYMENTS,
    SHOW_USER_SUBSCRIPTIONS,
    SHOW_EDITION_SEARCH_FORM,
    FIND_EDITIONS,
    ADD_SUBSCRIPTION,
    STOP_SUBSCRIPTION,
    BLOCK_EDITION,
    UNBLOCK_EDITION,
    UPDATE_EDITION,
    REFILL_USER_BALANCE
}
