-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 10:44:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `periodicals` ;

-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `periodicals` DEFAULT CHARACTER SET utf8 ;
USE `periodicals` ;

-- -----------------------------------------------------
-- Table `periodicals`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`edition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('Newspaper', 'Journal', 'Book') NOT NULL,
  `theme` VARCHAR(255) NOT NULL,
  `periodicity_per_year` INT(11) NOT NULL,
  `minimum_subscription_period_in_months` INT(11) NOT NULL,
  `price_for_minimum_subscription_period` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` ENUM('Admin', 'User') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `money` DECIMAL(19,4) NOT NULL,
  `is_available` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `user_role_fk` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `periodicals`.`user_role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`subscription` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `edition_id` INT(11) NOT NULL,
  `subscription_start_date` DATETIME NOT NULL,
  `subscription_end_date` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `edition_fk` (`edition_id` ASC) VISIBLE,
  INDEX `user_sub_fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `edition_fk`
    FOREIGN KEY (`edition_id`)
    REFERENCES `periodicals`.`edition` (`id`),
  CONSTRAINT `user_sub_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`payment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` ENUM('refill', 'payment', 'refund') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `type_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `subscription_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_fk` (`user_id` ASC) VISIBLE,
  INDEX `type_fk` (`type_id` ASC) VISIBLE,
  INDEX `subscription_fk` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `subscription_fk`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `periodicals`.`subscription` (`id`),
  CONSTRAINT `type_fk`
    FOREIGN KEY (`type_id`)
    REFERENCES `periodicals`.`payment_type` (`id`),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
