INSERT INTO edition_theme VALUES (1,"Автомобили. Транспорт");
INSERT INTO edition_theme VALUES (2,"Бизнес. Предпринимательство. Рынок");
INSERT INTO edition_theme VALUES (3,"Вооруженные Силы. Правоохранительные органы");
INSERT INTO edition_theme VALUES (4,"Государство и право. Юридические науки");
INSERT INTO edition_theme VALUES (5,"Детские и молодежные издания");
INSERT INTO edition_theme VALUES (6,"Досуг. Телепрограммы с анонсами");
INSERT INTO edition_theme VALUES (7,"Здравоохранение. Медицина");
INSERT INTO edition_theme VALUES (8,"Издания для женщин. Издания для мужчин");
INSERT INTO edition_theme VALUES (9,"Издания универсального содержания");
INSERT INTO edition_theme VALUES (10,"Книговедение. Полиграфия. Филателия");
INSERT INTO edition_theme VALUES (11,"Компьютерные издания. Телевидение. Радио. Связь");
INSERT INTO edition_theme VALUES (12,"Культура. Искусство. Литература");
INSERT INTO edition_theme VALUES (13,"Научные и научно-популярные издания");
INSERT INTO edition_theme VALUES (14,"Образование. Педагогика");
INSERT INTO edition_theme VALUES (15,"Общественно-политические и литературно-художественные издания");
INSERT INTO edition_theme VALUES (16,"Природа. Мир животных и растений");
INSERT INTO edition_theme VALUES (17,"Приусадебное хозяйство. Сельское хозяйство. Экология. Лесное хозяйство");
INSERT INTO edition_theme VALUES (18,"Рекламные издания");
INSERT INTO edition_theme VALUES (19,"Религиозные издания");
INSERT INTO edition_theme VALUES (20,"Социальная защита населения. Издания для инвалидов. Охрана труда. Кадровая служба.");
INSERT INTO edition_theme VALUES (21,"Спорт. Путешествия. Туризм");
INSERT INTO edition_theme VALUES (22,"Техника. Промышленность. Строительство. Архитектура. Дизайн");
INSERT INTO edition_theme VALUES (23,"Фантастика. Детектив");
INSERT INTO edition_theme VALUES (24,"Экономика и финансы");