-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 17:53:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `periodicals` ;

-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `periodicals` DEFAULT CHARACTER SET utf8 ;
USE `periodicals` ;

-- -----------------------------------------------------
-- Table `periodicals`.`edition_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`edition_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `periodicals`.`edition_type` (`id` ASC);


-- -----------------------------------------------------
-- Table `periodicals`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`edition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type_id` INT(11) NOT NULL,
  `theme_id` INT(11) NOT NULL,
  `periodicity_per_year` INT(11) NOT NULL,
  `minimum_subscription_period_in_months` INT(11) NOT NULL,
  `price_for_minimum_subscription_period` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `edition_type_fk`
    FOREIGN KEY (`type_id`)
    REFERENCES `periodicals`.`edition_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `periodicals`.`edition` (`id` ASC);

CREATE INDEX `edition_type_fk` ON `periodicals`.`edition` (`type_id` ASC);


-- -----------------------------------------------------
-- Table `periodicals`.`payment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` ENUM('refill', 'payment', 'refund') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `periodicals`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `password_hash` CHAR(64) NOT NULL,
  `money` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `periodicals`.`user_role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_role_fk` ON `periodicals`.`user` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `periodicals`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `type_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type_fk`
    FOREIGN KEY (`type_id`)
    REFERENCES `periodicals`.`payment_type` (`id`),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_fk` ON `periodicals`.`payment` (`user_id` ASC);

CREATE INDEX `type_fk` ON `periodicals`.`payment` (`type_id` ASC);


-- -----------------------------------------------------
-- Table `periodicals`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`subscription` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `edition_id` INT(11) NOT NULL,
  `subscription_start_date` DATETIME NOT NULL,
  `subscription_end_date` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `edition_fk`
    FOREIGN KEY (`edition_id`)
    REFERENCES `periodicals`.`edition` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `edition_fk` ON `periodicals`.`subscription` (`edition_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
